# Theme
version: v3.1.2

# Site Settings
name: "Whereyedo" # 사이트 이름
title: "Whereyedo" # 사이트 상단 HONE & 상단 TAB
description: "Whereyedo 기술블로그" # 사이트 설명으로 SEO(검색엔진)와 관계된 정보
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
#  - title: About
#    url: /about
#  - title: Contact
#    url: /contact
#  - title: Feed
#    url: /feed.xml
email: whereyedo@naver.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: whereyedo
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # 서브 경로
url: "https://whereyedo.github.io" # 인터넷에 공개되는 주소
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false # 우측 상산 Get this theme! 버튼 활성화 여부
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

translations:
  text:
    new_post: "New Post"
    see_also: "See also"
    search: "Search"
    author: "Author"
    share: "Share"
    comments: "Comments"
  button:
    read_now: "Read Now"
    share_on_twitter: "Share on Twitter"
    share_on_facebook: "Share on Facebook"
  pagination:
    page: "Page"
    of: "of"
    next_page: "Next Page"
    next_post: "Previous Page"
  recommendation:
    text: "Why don't you read something next?"
    back_btn: "Go back to top"
  error_404:
    title: "Page not found :("
    message: "I'm sorry. We couldn't find the page you are looking for."
    image_alt: "404 - Page not found"
  contact:
    title: "Talk to me"
    subject: "New contact!"
    submit_btn: "Send"
    placeholders:
      name: "Your name"
      email: "Your e-mail"
      message: "Your message"
    errors:
      locale: "en"
      empty_name: "Name is required"
      empty_email: "Email is required"
      invalid_email: "Email is invalid"
      empty_message: "Message is required"
    after_send:
      title: "Message sent!"
      message: "Thank you for sending me a message. I'm going to answer ASAP."
